/**
 * @file catalog.types.ts
 * @description Tipos compartidos del catálogo CharaTools.
 * Single source of truth para productos, filtros y categorías.
 */

// ---------------------------------------------------------------------------
// Variantes de producto (medidas, diámetros, calibres, etc.)
// ---------------------------------------------------------------------------

export interface ProductVariant {
  id?: string
  sku?: string
  /** Valor de la variante mostrado en el pill: "½\"", "¾\"", "#12", etc. */
  value: string
  /** Etiqueta alternativa de display (opcional — si difiere de value) */
  label?: string
  /** Marcar como agotado para deshabilitar el pill sin ocultarlo */
  outOfStock?: boolean
  price?: number
  status?: StockStatus
}

// ---------------------------------------------------------------------------
// Producto (catálogo B2B sin precios)
// ---------------------------------------------------------------------------

export type StockStatus = 'available' | 'high-demand' | 'new-batch' | 'out-of-stock'

export interface CatalogProduct {
  id: string
  /** URL slug legible para el router: /producto/[slug] */
  slug: string
  name: string
  shortDescription: string
  /** Descripción larga para la página/modal de detalle */
  description?: string
  category: string          // slug de categoría (ej: "herramientas-electricas")
  categoryLabel: string     // nombre legible (ej: "Herramientas Eléctricas")
  brand: string             // ej: "INGCO", "3M", "Stanley"
  reference?: string        // SKU/modelo
  unit: string              // "und", "m", "kg", "caja", "rollo"
  /** Potencia en vatios (para filtros de electricidad/herramientas) */
  powerWatts?: number
  /** Voltaje nominal */
  voltageVolts?: number
  /** Peso en kg */
  weightKg?: number
  image: string
  /** Imágenes adicionales para el detalle */
  gallery?: string[]
  status: StockStatus
  /** Etiquetas para búsqueda rápida */
  tags?: string[]
  /** Productos relacionados (IDs) para up-selling en modal */
  relatedIds?: string[]
  /** Flag para zona outlet/ofertas */
  isOutlet?: boolean
  /** Elegible para compra financiada con Cashea */
  isCasheaEligible?: boolean
  /** Precio sugerido para cálculos de Cashea (opcional en catálogo B2B) */
  price?: number
  /** Slug de la subcategoría (ej: 'tuberias', 'bombas') */
  subcategory?: string
  /** Nombre legible de la subcategoría (ej: 'Tuberías y Conexiones') */
  subcategoryLabel?: string
  /** Slug del sub-ítem de tercer nivel (ej: 'tuberia-sanitaria-estandar') */
  subitem?: string
  /** Nombre legible del sub-ítem (ej: 'Tubería Sanitaria Estándar') */
  subitemLabel?: string
  /**
   * Variantes seleccionables por medida/diámetro/calibre.
   * Cuando está definido, se muestra el selector de pills en la página de detalle.
   */
  variants?: ProductVariant[]
  /** Etiqueta del selector de variantes (ej: "Diámetro", "Calibre", "Longitud").
   * Por defecto: "Medida" si no se especifica.
   */
  variantLabel?: string
  /** Prioridad de ordenamiento (1: Tubería, 2: Conexión, etc.) */
  priority?: number
}

// ---------------------------------------------------------------------------
// Filtros (SearchParams)
// ---------------------------------------------------------------------------

export interface CatalogFilters {
  /** Marcas seleccionadas (multi-select) */
  marcas?: string[]
  /** Rango de potencia mínima en vatios */
  potenciaMin?: number
  /** Rango de potencia máxima en vatios */
  potenciaMax?: number
  /** Estado de stock */
  stock?: StockStatus[]
  /** Término de búsqueda libre */
  q?: string
  /** Filtro de elegibilidad Cashea */
  cashea?: 'true'
  /** Filtro de subcategoría o sub-ítem */
  sub?: string
}

// ---------------------------------------------------------------------------
// Categorías del catálogo
// ---------------------------------------------------------------------------

export interface CatalogCategory {
  slug: string
  label: string
  icon: string   // emoji o nombre de ícono Lucide
  description: string
}

export const CATALOG_CATEGORIES: CatalogCategory[] = [
  { slug: 'herramientas-electricas', label: 'Herramientas Eléctricas', icon: '⚡', description: 'Taladros, esmeriles, sierras y más' },
  { slug: 'herramientas-manuales',   label: 'Herramientas Manuales',   icon: '🔧', description: 'Destornilladores, llaves, martillos' },
  { slug: 'plomeria',                label: 'Plomería',                 icon: '🚿', description: 'Tuberías, válvulas, bombas, accesorios PPR' },
  { slug: 'electricidad',            label: 'Electricidad',             icon: '🔌', description: 'Cables, breakers, tableros, conectores' },
  { slug: 'iluminacion',             label: 'Iluminación',              icon: '💡', description: 'LED, paneles, reflectores, bombillos' },
  { slug: 'impermeabilizacion',      label: 'Impermeabilización',       icon: '🧴', description: 'Membranas, selladores, impermeabilizantes' },
  { slug: 'seguridad-industrial',    label: 'Seguridad Industrial',     icon: '🦺', description: 'Cascos, lentes, guantes, botas' },
]

// ---------------------------------------------------------------------------
// Marcas disponibles para filtros
// ---------------------------------------------------------------------------

export const CATALOG_BRANDS = [
  '3M',
  'Aquafina',
  'Bellota',
  'Belt-G',
  'Bosch',
  'Bridge',
  'Bticino',
  'Cebra',
  'Ceramipego',
  'Chopp',
  'Cobra',
  'Cross',
  'Dewalt',
  'Eagle',
  'Exxel',
  'Faguax',
  'Ferco',
  'Fermetal',
  'Genérico',
  'Griven',
  'Hammer',
  'Iconel',
  'INGCO',
  'Italy',
  'Joy',
  'Lincoln',
  'Littmann',
  'Lumistar',
  'Makita',
  'Manpica',
  'Ovni',
  'PCP',
  'Philips',
  'Piazza',
  'Plegable',
  'Prestige',
  'Protonic Electric',
  'Proxical',
  'Reinco',
  'Rek',
  'Run',
  'Sergeca',
  'Seven',
  'Spike',
  'Square',
  'Stanley',
  'Stone',
  'Tai',
  'Termofusion',
  'Time',
  'Tubrica',
  'Twist',
  'Venceramica',
  'Vert',
  'Vogue',
  'Zasc',
  'Zoe',
] as const

export type CatalogBrand = typeof CATALOG_BRANDS[number]

// ---------------------------------------------------------------------------
// Mock Data del Catálogo Completo
// Reemplazar por fetch real a API/CMS cuando estén listos
// ---------------------------------------------------------------------------

export const MOCK_PRODUCTS: CatalogProduct[] = [
  {
    id: 'taladro-ingco-550w',
    slug: 'taladro-ingco-550w',
    name: 'Taladro Percutor 550W INGCO',
    shortDescription: 'Taladro percutor profesional con 2 velocidades y chuck 13mm.',
    description: 'Ideal para concreto y mampostería. Motor de 550W, mandril de 13mm, 2 velocidades seleccionables, función percutor activable. Incluye maletín y broca de prueba.',
    category: 'herramientas-electricas',
    categoryLabel: 'Herramientas Eléctricas',
    brand: 'INGCO',
    reference: 'ID2228VRE',
    unit: 'und',
    powerWatts: 550,
    voltageVolts: 120,
    weightKg: 1.8,
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&q=80',
    status: 'available',
    tags: ['taladro', 'percutor', 'concreto', 'mampostería'],
    relatedIds: ['esmeril-ingco-820w', 'cable-electrico-2-100m'],
    isCasheaEligible: true,
    price: 45.00,
  },
  {
    id: 'esmeril-ingco-820w',
    slug: 'esmeril-ingco-820w',
    name: 'Esmeril Angular 820W 4½" INGCO',
    shortDescription: 'Esmeril profesional con disco de 115mm, 11,000 RPM.',
    category: 'herramientas-electricas',
    categoryLabel: 'Herramientas Eléctricas',
    brand: 'INGCO',
    reference: 'AG7508',
    unit: 'und',
    powerWatts: 820,
    voltageVolts: 120,
    weightKg: 1.9,
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&q=80',
    status: 'available',
    tags: ['esmeril', 'amoladora', 'corte', 'desbaste'],
    isOutlet: true,
    isCasheaEligible: true,
    price: 55.00,
  },
  {
    id: 'bomba-periferica-1-2hp',
    slug: 'bomba-periferica-1-2hp',
    name: 'Bomba de Agua Periférica 1/2 HP',
    shortDescription: 'Bomba centrífuga de alta eficiencia para riego y abastecimiento residencial.',
    description: 'Bomba periférica de 1/2 HP de alto rendimiento. Cuerpo en hierro fundido y acero inoxidable, motor de inducción a prueba de salpicaduras.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'bombas',
    subcategoryLabel: 'Bombas de Agua',
    subitem: 'bombas-perifericas',
    subitemLabel: 'Bombas Periféricas',
    brand: 'INGCO',
    reference: 'SPWP8001-12',
    unit: 'und',
    powerWatts: 370,
    voltageVolts: 120,
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&q=80',
    status: 'available',
    tags: ['bomba', 'agua', 'riego', 'presión'],
    isCasheaEligible: true,
    price: 35.00,
    priority: 1,
  },
  {
    id: 'bomba-periferica-3-4hp',
    slug: 'bomba-periferica-3-4hp',
    name: 'Bomba de Agua Periférica 3/4 HP',
    shortDescription: 'Bomba centrífuga de alta eficiencia para riego y abastecimiento residencial.',
    description: 'Bomba periférica de 3/4 HP de alto rendimiento. Cuerpo en hierro fundido y acero inoxidable, motor de inducción a prueba de salpicaduras.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'bombas',
    subcategoryLabel: 'Bombas de Agua',
    subitem: 'bombas-perifericas',
    subitemLabel: 'Bombas Periféricas',
    brand: 'INGCO',
    reference: 'SPWP8001-34',
    unit: 'und',
    powerWatts: 550,
    voltageVolts: 120,
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&q=80',
    status: 'available',
    tags: ['bomba', 'agua', 'riego', 'presión'],
    isCasheaEligible: true,
    price: 45.00,
    priority: 2,
  },
  {
    id: 'bomba-periferica-1hp',
    slug: 'bomba-periferica-1hp',
    name: 'Bomba de Agua Periférica 1 HP',
    shortDescription: 'Bomba centrífuga de alta eficiencia para riego y abastecimiento residencial.',
    description: 'Bomba periférica de 1 HP de alto rendimiento. Cuerpo en hierro fundido y acero inoxidable, motor de inducción a prueba de salpicaduras.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'bombas',
    subcategoryLabel: 'Bombas de Agua',
    subitem: 'bombas-perifericas',
    subitemLabel: 'Bombas Periféricas',
    brand: 'INGCO',
    reference: 'SPWP8001-1',
    unit: 'und',
    powerWatts: 750,
    voltageVolts: 120,
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&q=80',
    status: 'available',
    tags: ['bomba', 'agua', 'riego', 'presión'],
    isCasheaEligible: true,
    price: 55.00,
    priority: 3,
  },
  {
    id: 'bomba-centrifuga',
    slug: 'bomba-centrifuga',
    name: 'Bomba Centrífuga de Agua',
    shortDescription: 'Bomba centrífuga de alto caudal para suministro, elevación de agua limpia y sistemas hidroneumáticos.',
    description: 'Electrobomba centrífuga diseñada para transferir grandes volúmenes de agua limpia con flujo continuo y presión estable. Ideal para sistemas hidroneumáticos, riego, llenado de tanques elevados y abastecimiento en general.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'bombas',
    subcategoryLabel: 'Bombas de Agua',
    subitem: 'bombas-centrifugas',
    subitemLabel: 'Bombas Centrífugas',
    brand: 'Genérico',
    unit: 'und',
    image: '/categoria-plomeria.webp',
    status: 'available',
    tags: ['bomba', 'centrífuga', 'agua', 'alto caudal', 'presión', 'tanque', 'hidroneumático'],
    variantLabel: 'Potencia',
    variants: [
      { value: '1 HP' },
      { value: '2 HP' },
    ],
    priority: 4,
  },
  {
    id: 'tuberia-ppr-12',
    slug: 'tuberia-ppr-12',
    name: 'Tubería PPR para Aguas Blancas (Termofusión)',
    shortDescription: 'Tubería PPR PN20, resistente a altas temperaturas. Ideal para redes de agua caliente y fría en sistemas de termofusión.',
    description: 'La tubería PPR PN20 es la solución más duradera para instalaciones de agua caliente y fría. Compatible con todos los accesorios de termofusión. Alta resistencia química y mecánica, vida útil superior a 50 años. Disponible en tramos de 6 metros.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'tuberias-conexiones',
    subitem: 'termofusion-ppr',
    brand: 'Termofusion',
    unit: 'varilla (6m)',
    image: 'https://images.unsplash.com/photo-1581092162562-40038f72742b?w=400&q=80',
    status: 'available',
    tags: ['tubería', 'PPR', 'aguas blancas', 'termofusión', 'PN20'],
    variantLabel: 'Diámetro',
    variants: [
      { value: '½"' },
      { value: '¾"' },
      { value: '1"' },
      { value: '1¼"' },
      { value: '1½"' },
      { value: '2"' },
      { value: '3"', outOfStock: true },
    ],
  },
  {
    id: 'cable-electrico-thw',
    slug: 'cable-electrico-thw',
    name: 'Cable Eléctrico THW Certificado FONDONORMA',
    shortDescription: 'Cable THW x 100m, certificado FONDONORMA. Apto para instalaciones residenciales e industriales hasta 600V.',
    description: 'Cable de cobre sólido con aislamiento THW certificado por FONDONORMA. Resistente a humedad, aceites y temperaturas hasta 75°C. Disponible en múltiples calibres para adaptarse a cualquier instalación eléctrica residencial o industrial.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'cables',
    subcategoryLabel: 'Cables y Conductores',
    subitem: 'cables',
    subitemLabel: 'Cables y Conductores',
    brand: '3M',
    unit: 'rollo (100m)',
    voltageVolts: 600,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    status: 'available',
    priority: 1,
    tags: ['cable', 'eléctrico', 'THW', 'FONDONORMA', 'cobre'],
    variantLabel: 'Calibre',
    variants: [
      { value: '#14' },
      { value: '#12' },
      { value: '#10' },
      { value: '#8' },
      { value: '#6' },
      { value: '#4' },
      { value: '#2' },
      { value: '#1/0' },
      { value: '#2/0', outOfStock: true },
    ],
  },
  {
    id: 'breaker-30a',
    slug: 'breaker-30a',
    name: 'Breaker Termomagnético 30A',
    shortDescription: 'Disyuntor monofásico para tableros eléctricos residenciales.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Philips',
    reference: 'EZ9F34230',
    unit: 'und',
    voltageVolts: 240,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    status: 'new-batch',
    priority: 10,
    tags: ['breaker', 'disyuntor', 'tablero', 'protección'],
    isCasheaEligible: true,
    price: 12.00,
  },
  {
    id: 'bombillo-led-9w',
    slug: 'bombillo-led-9w',
    name: 'Bombillo LED 9W Luz Cálida E27',
    shortDescription: 'Bajo consumo, 800 lúmenes, vida útil 25,000 horas.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'focos-led',
    subcategoryLabel: 'Focos y Tubos LED',
    subitem: 'focos-led',
    subitemLabel: 'Focos y Tubos LED',
    brand: 'Philips',
    reference: 'LED927E27',
    unit: 'und',
    powerWatts: 9,
    voltageVolts: 120,
    image: 'https://images.unsplash.com/photo-1565636192335-14d0f48d7c71?w=400&q=80',
    status: 'available',
    tags: ['LED', 'bombillo', 'iluminación', 'E27'],
  },
  {
    id: 'panel-led-60w',
    slug: 'panel-led-60w',
    name: 'Panel LED Rectangular 60W',
    shortDescription: 'Panel empotrado, luz blanca neutra, driver incluido.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'focos-led',
    subcategoryLabel: 'Focos y Tubos LED',
    subitem: 'focos-led',
    subitemLabel: 'Focos y Tubos LED',
    brand: 'Philips',
    unit: 'und',
    powerWatts: 60,
    voltageVolts: 120,
    image: 'https://images.unsplash.com/photo-1565631969034-0e5c0f0e8c59?w=400&q=80',
    status: 'high-demand',
    tags: ['panel', 'LED', 'empotrado', 'oficina'],
    isOutlet: true,
  },
  {
    id: 'cinta-aislante-3m',
    slug: 'cinta-aislante-3m',
    name: 'Cinta Aislante Temflex 1700 3M (x10 und)',
    shortDescription: 'Cinta PVC negro, resistente hasta 600V, pack de 10.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tomacorrientes',
    subcategoryLabel: 'Tomacorrientes e Interruptores',
    subitem: 'tomacorrientes',
    subitemLabel: 'Tomacorrientes e Interruptores',
    brand: '3M',
    reference: 'TEMFLEX1700-10',
    unit: 'pack',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    status: 'available',
    priority: 11,
    tags: ['cinta', 'aislante', '3M', 'eléctrico'],
  },
  {
    id: 'flexometro-stanley-5m',
    slug: 'flexometro-stanley-5m',
    name: 'Flexómetro Classic 5m Stanley',
    shortDescription: 'Cinta métrica resistente, bloqueo automático, gancho magnético.',
    category: 'herramientas-manuales',
    categoryLabel: 'Herramientas Manuales',
    brand: 'Stanley',
    reference: '30-497',
    unit: 'und',
    weightKg: 0.3,
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&q=80',
    status: 'available',
    tags: ['flexómetro', 'medida', 'stanley', 'cinta métrica'],
  },
  {
    id: 'press-control-automatico',
    slug: 'press-control-automatico',
    name: 'Press Control Automático 1HP',
    shortDescription: 'Regulador de presión para sistemas de agua residencial.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'bombas',
    subcategoryLabel: 'Bombas de Agua',
    brand: 'INGCO',
    unit: 'und',
    powerWatts: 750,
    image: 'https://images.unsplash.com/photo-1585526881453-899142f58fd0?w=400&q=80',
    status: 'high-demand',
    tags: ['press control', 'presión', 'bomba', 'automático'],
    isCasheaEligible: true,
    price: 25.00,
  },
  {
    id: 'casco-seguridad-3m',
    slug: 'casco-seguridad-3m',
    name: 'Casco de Seguridad Industrial 3M',
    shortDescription: 'Casco tipo ratchet, ANSI Z89.1, resistente a impactos.',
    category: 'seguridad-industrial',
    categoryLabel: 'Seguridad Industrial',
    brand: '3M',
    unit: 'und',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&q=80',
    status: 'available',
    tags: ['casco', 'seguridad', 'protección', 'obra'],
  },
  {
    id: 'monomando-lavamanos-piazza-pico-alto',
    slug: 'monomando-lavamanos-piazza-pico-alto',
    name: 'Monomando Lavamanos Piazza (Pico Alto)',
    shortDescription: 'Monomando Lavamanos Piazza (Pico Alto) de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-altos',
    subitemLabel: 'Monomandos Altos',
    brand: 'Piazza',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Color / Acabado',
    variants: [
      { value: 'Cromo' },
      { value: 'Negro' },
      { value: 'Brushed' },
      { value: 'Rose Gold' },
      { value: 'Golden Brush' },
    ],
  },
  {
    id: 'monomando-lavamanos-prestige-pico-alto',
    slug: 'monomando-lavamanos-prestige-pico-alto',
    name: 'Monomando Lavamanos Prestige (Pico Alto)',
    shortDescription: 'Monomando Lavamanos Prestige (Pico Alto) de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-altos',
    subitemLabel: 'Monomandos Altos',
    brand: 'Prestige',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Color / Acabado',
    variants: [
      { value: 'Cromo' },
      { value: 'Negro' },
      { value: 'Brushed' },
      { value: 'Rose Gold' },
      { value: 'Golden Brush' },
    ],
  },
  {
    id: 'monomando-lavamanos-joy-pico-alto',
    slug: 'monomando-lavamanos-joy-pico-alto',
    name: 'Monomando Lavamanos Joy (Pico Alto)',
    shortDescription: 'Monomando Lavamanos Joy (Pico Alto) de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-altos',
    subitemLabel: 'Monomandos Altos',
    brand: 'Joy',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Color / Acabado',
    variants: [
      { value: 'Negro' },
      { value: 'Blanco' },
    ],
  },
  {
    id: 'monomando-lavamanos-modelo-piazza',
    slug: 'monomando-lavamanos-modelo-piazza',
    name: 'Monomando Lavamanos Modelo Piazza',
    shortDescription: 'Monomando Lavamanos Modelo Piazza de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-estandar',
    subitemLabel: 'Monomandos Estándar',
    brand: 'Piazza',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Color / Acabado',
    variants: [
      { value: 'Cromo' },
      { value: 'Negro' },
      { value: 'Brushed' },
      { value: 'Rose Gold' },
      { value: 'Golden Brush' },
    ],
  },
  {
    id: 'monomando-lavamanos-modelo-square',
    slug: 'monomando-lavamanos-modelo-square',
    name: 'Monomando Lavamanos Modelo Square',
    shortDescription: 'Monomando Lavamanos Modelo Square de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-estandar',
    subitemLabel: 'Monomandos Estándar',
    brand: 'Square',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Color / Acabado',
    variants: [
      { value: 'Cromo' },
      { value: 'Negro' },
      { value: 'Brushed' },
    ],
  },
  {
    id: 'monomando-lavamanos-modelo-zoe-360',
    slug: 'monomando-lavamanos-modelo-zoe-360',
    name: 'Monomando Lavamanos Modelo Zoe 360',
    shortDescription: 'Monomando Lavamanos Modelo Zoe 360 de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-estandar',
    subitemLabel: 'Monomandos Estándar',
    brand: 'Zoe',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'griferia-individual-1-solo-pomo-modelo-spike',
    slug: 'griferia-individual-1-solo-pomo-modelo-spike',
    name: 'Grifería Individual (1 solo pomo): Modelo Spike',
    shortDescription: 'Grifería Individual (1 solo pomo): Modelo Spike de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'grifos-individuales',
    subitemLabel: 'Grifos Individuales',
    brand: 'Spike',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'griferia-individual-1-solo-pomo-modelo-chopp',
    slug: 'griferia-individual-1-solo-pomo-modelo-chopp',
    name: 'Grifería Individual (1 solo pomo): Modelo Chopp',
    shortDescription: 'Grifería Individual (1 solo pomo): Modelo Chopp de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'grifos-individuales',
    subitemLabel: 'Grifos Individuales',
    brand: 'Chopp',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'griferia-individual-modelo-square-abs-plus',
    slug: 'griferia-individual-modelo-square-abs-plus',
    name: 'Grifería Individual Modelo Square (ABS Plus)',
    shortDescription: 'Grifería Individual Modelo Square (ABS Plus) de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'grifos-individuales',
    subitemLabel: 'Grifos Individuales',
    brand: 'Square',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Color / Acabado',
    variants: [
      { value: 'Negro' },
      { value: 'Blanco' },
    ],
  },
  {
    id: 'juegos-twin-8-doble-pomo-modelo-cross',
    slug: 'juegos-twin-8-doble-pomo-modelo-cross',
    name: 'Juegos Twin (8) doble pomo: modelo Cross',
    shortDescription: 'Juegos Twin (8) doble pomo: modelo Cross de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'juegos-twin',
    subitemLabel: 'Juegos Twin',
    brand: 'Cross',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'juegos-twin-8-doble-pomo-modelo-time',
    slug: 'juegos-twin-8-doble-pomo-modelo-time',
    name: 'Juegos Twin (8) doble pomo: modelo Time',
    shortDescription: 'Juegos Twin (8) doble pomo: modelo Time de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'juegos-twin',
    subitemLabel: 'Juegos Twin',
    brand: 'Time',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'lavamanos-valvula-temporizada-institucional',
    slug: 'lavamanos-valvula-temporizada-institucional',
    name: 'Lavamanos válvula temporizada institucional',
    shortDescription: 'Lavamanos válvula temporizada institucional de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'griferia-institucional',
    subitemLabel: 'Grifería Institucional',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'monomando-modelo-bridge-resorte-metalico',
    slug: 'monomando-modelo-bridge-resorte-metalico',
    name: 'Monomando Modelo Bridge Resorte Metálico',
    shortDescription: 'Monomando Modelo Bridge Resorte Metálico de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-profesionales',
    subitemLabel: 'Monomandos Profesionales (Línea Chef / Resorte)',
    brand: 'Bridge',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'monomando-modelo-bridge-flexible',
    slug: 'monomando-modelo-bridge-flexible',
    name: 'Monomando Modelo Bridge Flexible',
    shortDescription: 'Monomando Modelo Bridge Flexible de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-profesionales',
    subitemLabel: 'Monomandos Profesionales (Línea Chef / Resorte)',
    brand: 'Bridge',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'monomando-modelo-bridge-black',
    slug: 'monomando-modelo-bridge-black',
    name: 'Monomando Modelo Bridge Black',
    shortDescription: 'Monomando Modelo Bridge Black de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-profesionales',
    subitemLabel: 'Monomandos Profesionales (Línea Chef / Resorte)',
    brand: 'Bridge',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Color / Acabado',
    variants: [
      { value: 'Negro' },
    ],
  },
  {
    id: 'monomando-modelo-hammer-extensible',
    slug: 'monomando-modelo-hammer-extensible',
    name: 'Monomando Modelo Hammer Extensible',
    shortDescription: 'Monomando Modelo Hammer Extensible de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-extensibles',
    subitemLabel: 'Monomandos Extensibles (Manguera extraíble)',
    brand: 'Hammer',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'monomando-modelo-rek-extensible',
    slug: 'monomando-modelo-rek-extensible',
    name: 'Monomando Modelo Rek Extensible',
    shortDescription: 'Monomando Modelo Rek Extensible de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-extensibles',
    subitemLabel: 'Monomandos Extensibles (Manguera extraíble)',
    brand: 'Rek',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'monomando-modelo-vogue-extensible',
    slug: 'monomando-modelo-vogue-extensible',
    name: 'Monomando Modelo Vogue Extensible',
    shortDescription: 'Monomando Modelo Vogue Extensible de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-extensibles',
    subitemLabel: 'Monomandos Extensibles (Manguera extraíble)',
    brand: 'Vogue',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'monomando-modelo-twist-extensible',
    slug: 'monomando-modelo-twist-extensible',
    name: 'Monomando Modelo Twist Extensible',
    shortDescription: 'Monomando Modelo Twist Extensible de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'monomandos-extensibles',
    subitemLabel: 'Monomandos Extensibles (Manguera extraíble)',
    brand: 'Twist',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'fregadero-monomando-pico-cisne-modelo-joy',
    slug: 'fregadero-monomando-pico-cisne-modelo-joy',
    name: 'Fregadero Monomando Pico Cisne Modelo Joy',
    shortDescription: 'Fregadero Monomando Pico Cisne Modelo Joy de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'cuello-cisne-tradicional',
    subitemLabel: 'Cuello de Cisne Tradicional (Fijos / Al mesón)',
    brand: 'Joy',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'grifo-fregadero-monomando-modelo-ovni',
    slug: 'grifo-fregadero-monomando-modelo-ovni',
    name: 'Grifo Fregadero Monomando Modelo Ovni',
    shortDescription: 'Grifo Fregadero Monomando Modelo Ovni de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'cuello-cisne-tradicional',
    subitemLabel: 'Cuello de Cisne Tradicional (Fijos / Al mesón)',
    brand: 'Ovni',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'monomando-fregadero-cuello-cisne-modelo-tai',
    slug: 'monomando-fregadero-cuello-cisne-modelo-tai',
    name: 'Monomando Fregadero Cuello Cisne Modelo Tai',
    shortDescription: 'Monomando Fregadero Cuello Cisne Modelo Tai de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'cuello-cisne-tradicional',
    subitemLabel: 'Cuello de Cisne Tradicional (Fijos / Al mesón)',
    brand: 'Tai',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'monomando-fregadero-pared-empotrar-modelo-joy',
    slug: 'monomando-fregadero-pared-empotrar-modelo-joy',
    name: 'Monomando Fregadero Pared Empotrar Modelo Joy',
    shortDescription: 'Monomando Fregadero Pared Empotrar Modelo Joy de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'griferias-instalacion-pared',
    subitemLabel: 'Griferías para Instalación a Pared',
    brand: 'Joy',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'monomando-fregadero-pared-empotrar-modelo-plegable',
    slug: 'monomando-fregadero-pared-empotrar-modelo-plegable',
    name: 'Monomando Fregadero Pared Empotrar Modelo Plegable',
    shortDescription: 'Monomando Fregadero Pared Empotrar Modelo Plegable de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'griferias-instalacion-pared',
    subitemLabel: 'Griferías para Instalación a Pared',
    brand: 'Plegable',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'grifo-pared-monomando-modelo-square-cisne',
    slug: 'grifo-pared-monomando-modelo-square-cisne',
    name: 'Grifo Pared Monomando Modelo Square Cisne',
    shortDescription: 'Grifo Pared Monomando Modelo Square Cisne de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'griferias-instalacion-pared',
    subitemLabel: 'Griferías para Instalación a Pared',
    brand: 'Square',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'grifo-fregadero-pico-modelo-seven',
    slug: 'grifo-fregadero-pico-modelo-seven',
    name: 'Grifo Fregadero Pico Modelo Seven',
    shortDescription: 'Grifo Fregadero Pico Modelo Seven de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'mezcladoras-grifos-individuales',
    subitemLabel: 'Mezcladoras Doble Manilla y Grifos Individuales',
    brand: 'Seven',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'grifo-fregadero-pico-cisne-eagle',
    slug: 'grifo-fregadero-pico-cisne-eagle',
    name: 'Grifo Fregadero Pico Cisne Eagle',
    shortDescription: 'Grifo Fregadero Pico Cisne Eagle de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'mezcladoras-grifos-individuales',
    subitemLabel: 'Mezcladoras Doble Manilla y Grifos Individuales',
    brand: 'Eagle',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'grifo-fregadero-pico-cisne-chopp',
    slug: 'grifo-fregadero-pico-cisne-chopp',
    name: 'Grifo Fregadero Pico Cisne Chopp',
    shortDescription: 'Grifo Fregadero Pico Cisne Chopp de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'mezcladoras-grifos-individuales',
    subitemLabel: 'Mezcladoras Doble Manilla y Grifos Individuales',
    brand: 'Chopp',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'llave-de-arresto-modelo-square',
    slug: 'llave-de-arresto-modelo-square',
    name: 'Llave de Arresto Modelo Square',
    shortDescription: 'Llave de Arresto Modelo Square de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'llaves-arresto',
    subitemLabel: 'Llaves de Arresto (Pared)',
    brand: 'Square',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'llave-de-arresto-modelo-stone',
    slug: 'llave-de-arresto-modelo-stone',
    name: 'Llave de Arresto Modelo Stone',
    shortDescription: 'Llave de Arresto Modelo Stone de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'llaves-arresto',
    subitemLabel: 'Llaves de Arresto (Pared)',
    brand: 'Stone',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'llave-de-arresto-doble-salida',
    slug: 'llave-de-arresto-doble-salida',
    name: 'Llave de Arresto Doble Salida',
    shortDescription: 'Llave de Arresto Doble Salida de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'llaves-arresto',
    subitemLabel: 'Llaves de Arresto (Pared)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'llave-de-arresto-12x38',
    slug: 'llave-de-arresto-12x38',
    name: 'Llave de Arresto 1/2x3/8',
    shortDescription: 'Llave de Arresto 1/2x3/8 de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'llaves-arresto',
    subitemLabel: 'Llaves de Arresto (Pared)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
    ],
  },
  {
    id: 'valvulas-de-compuerta-bronceroja-pesadas',
    slug: 'valvulas-de-compuerta-bronceroja-pesadas',
    name: 'Válvulas de Compuerta (Bronce/Roja): Pesadas',
    shortDescription: 'Válvulas de Compuerta (Bronce/Roja): Pesadas de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-industriales-pesadas',
    subitemLabel: 'Válvulas Industriales y Pesadas (Metal)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
    ],
  },
  {
    id: 'valvula-de-compuerta-bronceroja-estandar',
    slug: 'valvula-de-compuerta-bronceroja-estandar',
    name: 'Válvula de Compuerta (Bronce/Roja): Estándar',
    shortDescription: 'Válvula de Compuerta (Bronce/Roja): Estándar de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-industriales-pesadas',
    subitemLabel: 'Válvulas Industriales y Pesadas (Metal)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
    ],
  },
  {
    id: 'valvula-de-bola-metalica-12-34-1-1-12-2-3-4',
    slug: 'valvula-de-bola-metalica-12-34-1-1-12-2-3-4',
    name: 'Válvula de Bola Metálica: 1/2, 3/4, 1, 1 1/2, 2, 3, 4',
    shortDescription: 'Válvula de Bola Metálica: 1/2, 3/4, 1, 1 1/2, 2, 3, 4 de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-industriales-pesadas',
    subitemLabel: 'Válvulas Industriales y Pesadas (Metal)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
      { value: '¾"' },
      { value: '1½"' },
    ],
  },
  {
    id: 'llaves-de-bola-12',
    slug: 'llaves-de-bola-12',
    name: 'Llaves de Bola: 1/2',
    shortDescription: 'Llaves de Bola: 1/2 de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-industriales-pesadas',
    subitemLabel: 'Válvulas Industriales y Pesadas (Metal)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
    ],
  },
  {
    id: 'valvulas-de-bola-pvc-pegarsoldar-12-34-1-1-12-2-3-4',
    slug: 'valvulas-de-bola-pvc-pegarsoldar-12-34-1-1-12-2-3-4',
    name: 'Válvulas de Bola PVC (Pegar/Soldar): 1/2, 3/4, 1, 1 1/2, 2, 3, 4',
    shortDescription: 'Válvulas de Bola PVC (Pegar/Soldar): 1/2, 3/4, 1, 1 1/2, 2, 3, 4 de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-pvc',
    subitemLabel: 'Línea de Válvulas PVC (Plástico)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
      { value: '¾"' },
      { value: '1½"' },
    ],
  },
  {
    id: 'valvulas-de-bola-pvc-roscar-12-a-4',
    slug: 'valvulas-de-bola-pvc-roscar-12-a-4',
    name: 'Válvulas de Bola PVC (Roscar): 1/2 a 4',
    shortDescription: 'Válvulas de Bola PVC (Roscar): 1/2 a 4 de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-pvc',
    subitemLabel: 'Línea de Válvulas PVC (Plástico)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
    ],
  },
  {
    id: 'valvula-de-bola-tipo-doble-union-universal',
    slug: 'valvula-de-bola-tipo-doble-union-universal',
    name: 'Válvula de Bola Tipo Doble Unión Universal',
    shortDescription: 'Válvula de Bola Tipo Doble Unión Universal de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-pvc',
    subitemLabel: 'Línea de Válvulas PVC (Plástico)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'valvula-de-bola-tipo-doble-union-rosca',
    slug: 'valvula-de-bola-tipo-doble-union-rosca',
    name: 'Válvula de Bola Tipo Doble Unión Rosca',
    shortDescription: 'Válvula de Bola Tipo Doble Unión Rosca de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-pvc',
    subitemLabel: 'Línea de Válvulas PVC (Plástico)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'valvulas-de-retencion-12-a-4',
    slug: 'valvulas-de-retencion-12-a-4',
    name: 'Válvulas de Retención: 1/2 a 4',
    shortDescription: 'Válvulas de Retención: 1/2 a 4 de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-retencion-especiales',
    subitemLabel: 'Válvulas de Retención y Especiales (Check)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
    ],
  },
  {
    id: 'valvulas-de-retencion-swing-check-gualeta-12-a-4',
    slug: 'valvulas-de-retencion-swing-check-gualeta-12-a-4',
    name: 'Válvulas de Retención (Swing Check / Gualeta): 1/2 a 4',
    shortDescription: 'Válvulas de Retención (Swing Check / Gualeta): 1/2 a 4 de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-retencion-especiales',
    subitemLabel: 'Válvulas de Retención y Especiales (Check)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
    ],
  },
  {
    id: 'valvulas-check-con-resorte-foot-valve',
    slug: 'valvulas-check-con-resorte-foot-valve',
    name: 'Válvulas Check con Resorte (Foot Valve)',
    shortDescription: 'Válvulas Check con Resorte (Foot Valve) de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-retencion-especiales',
    subitemLabel: 'Válvulas de Retención y Especiales (Check)',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'valvulas-reductoras-de-presion-modelo-italy',
    slug: 'valvulas-reductoras-de-presion-modelo-italy',
    name: 'Válvulas Reductoras de Presión Modelo Italy',
    shortDescription: 'Válvulas Reductoras de Presión Modelo Italy de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'valvulas-retencion-especiales',
    subitemLabel: 'Válvulas de Retención y Especiales (Check)',
    brand: 'Italy',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'llave-de-chorro-12-de-bronce',
    slug: 'llave-de-chorro-12-de-bronce',
    name: 'Llave de Chorro 1/2 de Bronce',
    shortDescription: 'Llave de Chorro 1/2 de Bronce de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'llaves-chorro-manguera',
    subitemLabel: 'Llaves de Chorro y Manguera',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
    ],
  },
  {
    id: 'llave-de-chorro-12-cromada-de-lujo',
    slug: 'llave-de-chorro-12-cromada-de-lujo',
    name: 'Llave de Chorro 1/2 Cromada de Lujo',
    shortDescription: 'Llave de Chorro 1/2 Cromada de Lujo de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'llaves-chorro-manguera',
    subitemLabel: 'Llaves de Chorro y Manguera',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
    ],
  },
  {
    id: 'llave-de-chorro-12-plastica-economica',
    slug: 'llave-de-chorro-12-plastica-economica',
    name: 'Llave de Chorro 1/2 Plástica Económica',
    shortDescription: 'Llave de Chorro 1/2 Plástica Económica de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'llaves-chorro-manguera',
    subitemLabel: 'Llaves de Chorro y Manguera',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
    variantLabel: 'Medida',
    variants: [
      { value: '½"' },
    ],
  },
  {
    id: 'llave-de-chorro-camello-de-lujo',
    slug: 'llave-de-chorro-camello-de-lujo',
    name: 'Llave de Chorro Camello de Lujo',
    shortDescription: 'Llave de Chorro Camello de Lujo de excelente calidad y alta durabilidad.',
    category: 'plomeria',
    categoryLabel: 'Plomería',
    subcategory: 'griferia',
    subcategoryLabel: 'Grifería y Válvulas',
    subitem: 'llaves-chorro-manguera',
    subitemLabel: 'Llaves de Chorro y Manguera',
    brand: 'Genérico',
    unit: 'und',
    image: '/griferia.webp',
    status: 'available',
    isCasheaEligible: true,
  },
  {
    id: 'bombillo-bulbo-led',
    slug: 'bombillo-bulbo-led',
    name: 'Bombillo LED Bulbo',
    shortDescription: 'Bombillo LED tipo bulbo de bajo consumo con luz clara y constante para iluminación residencial y comercial.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'focos-led',
    subcategoryLabel: 'Focos y Tubos LED',
    subitem: 'focos-led',
    subitemLabel: 'Focos y Tubos LED',
    brand: 'Genérico',
    unit: 'und',
    image: 'https://xnxvoehkqqkhlzknccnr.supabase.co/storage/v1/object/public/product-images/productos/1786893353268-bombillo-bulbo-jpeg.jpeg',
    status: 'available',
    priority: 1,
    tags: ['LED', 'bombillo', 'bulbo', 'iluminación', 'foco', 'E27'],
    variantLabel: 'Potencia',
    variants: [
      { value: '5W' },
      { value: '7W' },
      { value: '9W' },
      { value: '12W' },
      { value: '15W' },
      { value: '18W' },
      { value: '20W' },
    ],
  },
  {
    id: 'bombillo-domo-led',
    slug: 'bombillo-domo-led',
    name: 'Bombillo LED Domo',
    shortDescription: 'Bombillo LED formato domo de alta potencia y amplio ángulo de iluminación para grandes áreas.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'focos-led',
    subcategoryLabel: 'Focos y Tubos LED',
    subitem: 'focos-led',
    subitemLabel: 'Focos y Tubos LED',
    brand: 'Genérico',
    unit: 'und',
    image: '/iluminacion.webp',
    status: 'available',
    priority: 2,
    tags: ['LED', 'bombillo', 'domo', 'alta potencia', 'iluminación'],
    variantLabel: 'Potencia',
    variants: [
      { value: '20W' },
      { value: '30W' },
      { value: '40W' },
      { value: '50W' },
      { value: '60W' },
      { value: '80W' },
    ],
  },
  {
    id: 'bombillo-industrial-led',
    slug: 'bombillo-industrial-led',
    name: 'Bombillo LED Industrial',
    shortDescription: 'Bombillo LED industrial de alta potencia para galpones, talleres y áreas de trabajo exigentes.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'focos-led',
    subcategoryLabel: 'Focos y Tubos LED',
    subitem: 'focos-led',
    subitemLabel: 'Focos y Tubos LED',
    brand: 'Genérico',
    unit: 'und',
    image: '/iluminacion.webp',
    status: 'available',
    tags: ['LED', 'industrial', 'bombillo', 'alta potencia', 'galpón'],
    variantLabel: 'Potencia',
    variants: [
      { value: '90W' },
      { value: '100W' },
      { value: '150W' },
    ],
  },
  {
    id: 'bombillo-vela-led',
    slug: 'bombillo-vela-led',
    name: 'Bombillo LED Vela',
    shortDescription: 'Bombillo LED tipo vela decorativo disponible en roscas E-27 y E-14 para lámparas y apliques.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'focos-led',
    subcategoryLabel: 'Focos y Tubos LED',
    subitem: 'focos-led',
    subitemLabel: 'Focos y Tubos LED',
    brand: 'Genérico',
    unit: 'und',
    image: '/iluminacion.webp',
    status: 'available',
    priority: 3,
    tags: ['LED', 'vela', 'bombillo', 'E-27', 'E-14', 'decorativo'],
    variantLabel: 'Rosca / Base',
    variants: [
      { value: 'E-27' },
      { value: 'E-14' },
    ],
  },
  {
    id: 'tubo-led',
    slug: 'tubo-led',
    name: 'Tubo LED',
    shortDescription: 'Tubo LED de alto rendimiento para iluminación lineal continua en oficinas, comercios y galpones.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'focos-led',
    subcategoryLabel: 'Focos y Tubos LED',
    subitem: 'focos-led',
    subitemLabel: 'Focos y Tubos LED',
    brand: 'Genérico',
    unit: 'und',
    image: '/iluminacion.webp',
    status: 'available',
    priority: 4,
    tags: ['LED', 'tubo', 'lineal', '60cm', '120cm', 'iluminación'],
    variantLabel: 'Longitud',
    variants: [
      { value: '60 cm' },
      { value: '120 cm' },
    ],
  },
  {
    id: 'reflector-led',
    slug: 'reflector-led',
    name: 'Reflector LED',
    shortDescription: 'Reflector LED estanco resistente al agua y a la intemperie para fachadas, patios e industria.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'focos-led',
    subcategoryLabel: 'Focos y Tubos LED',
    subitem: 'focos-led',
    subitemLabel: 'Focos y Tubos LED',
    brand: 'Genérico',
    unit: 'und',
    image: '/iluminacion.webp',
    status: 'available',
    priority: 8,
    tags: ['LED', 'reflector', 'exterior', 'IP65', 'proyector', 'potencia'],
    variantLabel: 'Potencia',
    variants: [
      { value: '10W' },
      { value: '20W' },
      { value: '30W' },
      { value: '40W' },
      { value: '50W' },
      { value: '100W' },
      { value: '150W' },
      { value: '200W' },
      { value: '300W' },
      { value: '400W' },
    ],
  },
  {
    id: 'reflector-led-panel-solar',
    slug: 'reflector-led-panel-solar',
    name: 'Reflector LED Panel Solar 100W',
    shortDescription: 'Reflector solar LED de 100W con panel solar independiente, encendido automático y control remoto.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'focos-led',
    subcategoryLabel: 'Focos y Tubos LED',
    subitem: 'focos-led',
    subitemLabel: 'Focos y Tubos LED',
    brand: 'Genérico',
    unit: 'und',
    image: '/iluminacion.webp',
    status: 'available',
    priority: 9,
    tags: ['LED', 'reflector', 'solar', 'panel solar', '100W', 'autónomo'],
    variantLabel: 'Potencia',
    variants: [
      { value: '100W' },
    ],
  },
  {
    id: 'bombillo-dicroico-bi-pin',
    slug: 'bombillo-dicroico-bi-pin',
    name: 'Bombillo Dicroico Bi-Pin',
    shortDescription: 'Bombillo dicroico LED tipo Bi-Pin de luz dirigida para acento visual en nichos, techos y vitrinas.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'focos-led',
    subcategoryLabel: 'Focos y Tubos LED',
    subitem: 'focos-led',
    subitemLabel: 'Focos y Tubos LED',
    brand: 'Genérico',
    unit: 'und',
    image: '/iluminacion.webp',
    status: 'available',
    priority: 6,
    tags: ['LED', 'dicroico', 'bi-pin', 'ojo de buey', 'spot', 'foco'],
    variantLabel: 'Potencia',
    variants: [
      { value: '5W' },
      { value: '7W' },
    ],
  },
  {
    id: 'bombillo-dicroico-gu-10',
    slug: 'bombillo-dicroico-gu-10',
    name: 'Bombillo Dicroico GU-10',
    shortDescription: 'Bombillo dicroico LED base GU-10 de bajo consumo para iluminación direccional en ojos de buey.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'focos-led',
    subcategoryLabel: 'Focos y Tubos LED',
    subitem: 'focos-led',
    subitemLabel: 'Focos y Tubos LED',
    brand: 'Genérico',
    unit: 'und',
    image: '/iluminacion.webp',
    status: 'available',
    tags: ['LED', 'dicroico', 'GU10', 'ojo de buey', 'spot', 'foco'],
    variantLabel: 'Potencia',
    variants: [
      { value: '5W' },
      { value: '7W' },
    ],
  },
  {
    id: 'lampara-emergencia-led-lumistar-6w',
    slug: 'lampara-emergencia-led-lumistar-6w',
    name: 'Lámpara de Emergencia LED Lumistar 6W Multivoltaje',
    shortDescription: 'Lámpara de emergencia LED Lumistar 6W multivoltaje (85-265V) con autonomía de hasta 3 horas y doble faro orientable.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'emergencia',
    subcategoryLabel: 'Lámparas de Emergencia',
    subitem: 'emergencia',
    subitemLabel: 'Lámparas de Emergencia',
    brand: 'Lumistar',
    unit: 'und',
    image: '/iluminacion.webp',
    status: 'available',
    priority: 1,
    tags: ['LED', 'lámpara', 'emergencia', 'Lumistar', '6W', 'recargable', 'multivoltaje', '3 horas'],
    powerWatts: 6,
    variantLabel: 'Potencia',
    variants: [
      { value: '6W' },
    ],
  },
  {
    id: 'bombillo-led-emergencia-9w-recargable',
    slug: 'bombillo-led-emergencia-9w-recargable',
    name: 'Bombillo LED de Emergencia Recargable 9W',
    shortDescription: 'Bombillo LED recargable de emergencia 9W multivoltaje (85-265V) 6500K blanco frío con socket y gancho portátil.',
    category: 'iluminacion',
    categoryLabel: 'Iluminación',
    subcategory: 'emergencia',
    subcategoryLabel: 'Lámparas de Emergencia',
    subitem: 'emergencia',
    subitemLabel: 'Lámparas de Emergencia',
    brand: 'Lumistar',
    unit: 'und',
    image: '/iluminacion.webp',
    status: 'available',
    priority: 2,
    tags: ['LED', 'bombillo', 'emergencia', 'recargable', '9W', 'Lumistar', '6500K', 'gancho portátil'],
    powerWatts: 9,
    variantLabel: 'Potencia',
    variants: [
      { value: '9W' },
    ],
  },
  {
    id: 'cable-tsn-st',
    slug: 'cable-tsn-st',
    name: 'Cable TSN - ST',
    shortDescription: 'Cable multifilar flexible tipo TSN - ST de cobre para conexiones móviles, equipos de potencia e industrias.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'cables',
    subcategoryLabel: 'Cables y Conductores',
    subitem: 'cables',
    subitemLabel: 'Cables y Conductores',
    brand: 'Genérico',
    unit: 'm',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 2,
    tags: ['cable', 'TSN', 'ST', 'goma', 'cobre', 'eléctrico', 'potencia'],
    variantLabel: 'Calibre / Medida',
    variants: [
      { value: '3x14' },
      { value: '3x12' },
      { value: '3x10' },
      { value: '3x08' },
      { value: '2x12' },
      { value: '2x10' },
    ],
  },
  {
    id: 'cable-thw-thhn',
    slug: 'cable-thw-thhn',
    name: 'Cable THW / THHN',
    shortDescription: 'Cable monopolar de cobre suave con aislamiento termoplástico THW / THHN para acometidas y tableros eléctricos.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'cables',
    subcategoryLabel: 'Cables y Conductores',
    subitem: 'cables',
    subitemLabel: 'Cables y Conductores',
    brand: 'Iconel',
    unit: 'm',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 3,
    tags: ['cable', 'THW', 'THHN', 'monopolar', 'cobre', 'eléctrico', 'AWG'],
    variantLabel: 'Calibre',
    variants: [
      { value: '14 AWG' },
      { value: '12 AWG' },
      { value: '10 AWG' },
      { value: '8 AWG' },
      { value: '6 AWG' },
    ],
  },
  {
    id: 'cable-spt-cobre',
    slug: 'cable-spt-cobre',
    name: 'Cable SPT (100% Cobre Nacional)',
    shortDescription: 'Cable dúplex flexible tipo SPT 100% cobre nacional para extensiones, iluminación y electrodomésticos.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'cables',
    subcategoryLabel: 'Cables y Conductores',
    subitem: 'cables',
    subitemLabel: 'Cables y Conductores',
    brand: 'Genérico',
    unit: 'm',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 4,
    tags: ['cable', 'SPT', 'dúplex', 'cobre', 'eléctrico', 'extensión'],
    variantLabel: 'Calibre',
    variants: [
      { value: '2x18 AWG' },
      { value: '2x16 AWG' },
      { value: '2x14 AWG' },
      { value: '2x12 AWG' },
      { value: '2x10 AWG' },
    ],
  },
  {
    id: 'cable-coaxial-rg6',
    slug: 'cable-coaxial-rg6',
    name: 'Cable Coaxial RG6',
    shortDescription: 'Cable coaxial RG6 blindado de alta frecuencia para televisión por cable, antenas y redes de telecomunicación.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'cables',
    subcategoryLabel: 'Cables y Conductores',
    subitem: 'cables',
    subitemLabel: 'Cables y Conductores',
    brand: 'Genérico',
    unit: 'm',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 5,
    tags: ['cable', 'coaxial', 'RG6', 'TV', 'antena', 'telecomunicaciones'],
    variantLabel: 'Color',
    variants: [
      { value: 'Blanco' },
      { value: 'Negro' },
    ],
  },
  {
    id: 'tablero-electrico-sin-puerta',
    slug: 'tablero-electrico-sin-puerta',
    name: 'Tablero Eléctrico Sin Puerta',
    shortDescription: 'Tablero de distribución eléctrica metálico sin puerta para breakers residenciales y comerciales.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Genérico',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 1,
    tags: ['tablero', 'distribución', 'eléctrico', 'sin puerta', 'circuitos', 'breaker'],
    variantLabel: 'Circuitos',
    variants: [
      { value: '2 Circuitos' },
      { value: '4 Circuitos' },
      { value: '6 Circuitos' },
    ],
  },
  {
    id: 'tablero-electrico-con-puerta',
    slug: 'tablero-electrico-con-puerta',
    name: 'Tablero Eléctrico Con Puerta',
    shortDescription: 'Tablero metálico de distribución con puerta frontal para protección de breakers en instalaciones eléctricas.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Genérico',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 2,
    tags: ['tablero', 'distribución', 'con puerta', 'eléctrico', 'circuitos', 'breaker', 'metálico'],
    variantLabel: 'Circuitos',
    variants: [
      { value: '4 Circuitos' },
      { value: '6 Circuitos' },
      { value: '8 Circuitos' },
      { value: '12 Circuitos' },
    ],
  },
  {
    id: 'tablero-termomagnetico-riel-din',
    slug: 'tablero-termomagnetico-riel-din',
    name: 'Tablero Termomagnético Riel DIN',
    shortDescription: 'Caja y tablero de distribución en PVC para interruptores termomagnéticos riel DIN de 1 a 8 circuitos.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Genérico',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 3,
    tags: ['tablero', 'termomagnético', 'riel DIN', 'PVC', 'distribución', 'breaker'],
    variantLabel: 'Circuitos',
    variants: [
      { value: '1 Circuito' },
      { value: '2 Circuitos' },
      { value: '4 Circuitos' },
      { value: '6 Circuitos' },
      { value: '8 Circuitos' },
    ],
  },
  {
    id: 'tablero-termomagnetico-puerta-fume',
    slug: 'tablero-termomagnetico-puerta-fume',
    name: 'Tablero Termomagnético con Puerta Fumé (Empotrable y Superficial)',
    shortDescription: 'Tablero de distribución modular con tapa / puerta acrílica fumé transparente para montaje superficial o empotrable.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Genérico',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 4,
    tags: ['tablero', 'termomagnético', 'puerta fumé', 'empotrable', 'superficial', 'acrílico', 'breaker', 'distribución'],
    variantLabel: 'Circuitos',
    variants: [
      { value: '2 Circuitos' },
      { value: '4 Circuitos' },
      { value: '8 Circuitos' },
      { value: '10 Circuitos' },
      { value: '12 Circuitos' },
      { value: '24 Circuitos' },
    ],
  },
  {
    id: 'breaker-thqc-superficial-1-polo',
    slug: 'breaker-thqc-superficial-1-polo',
    name: 'Breaker THQC Superficial 1 Polo',
    shortDescription: 'Interruptor termomagnético tipo THQC superficial (atornillable) monofásico de 1 polo para tableros eléctricos.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Exceline',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 5,
    tags: ['breaker', 'THQC', 'superficial', 'atornillable', '1 polo', 'termomagnético', 'disyuntor', 'electricidad'],
    variantLabel: 'Amperaje',
    variants: [
      { value: '15A' },
      { value: '20A' },
      { value: '30A' },
      { value: '40A' },
      { value: '50A' },
      { value: '60A' },
    ],
  },
  {
    id: 'breaker-thqc-superficial-2-polos',
    slug: 'breaker-thqc-superficial-2-polos',
    name: 'Breaker THQC Superficial 2 Polos',
    shortDescription: 'Interruptor termomagnético tipo THQC superficial (atornillable) bifásico de 2 polos para protección de 240V.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Exceline',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 6,
    tags: ['breaker', 'THQC', 'superficial', 'atornillable', '2 polos', 'bifásico', 'termomagnético', 'electricidad'],
    variantLabel: 'Amperaje',
    variants: [
      { value: '20A' },
      { value: '30A' },
      { value: '40A' },
      { value: '50A' },
      { value: '60A' },
      { value: '70A' },
      { value: '100A' },
    ],
  },
  {
    id: 'breaker-thqc-superficial-3-polos',
    slug: 'breaker-thqc-superficial-3-polos',
    name: 'Breaker THQC Superficial 3 Polos',
    shortDescription: 'Interruptor termomagnético tipo THQC superficial (atornillable) trifásico de 3 polos para tableros industriales.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Exceline',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 7,
    tags: ['breaker', 'THQC', 'superficial', 'atornillable', '3 polos', 'trifásico', 'termomagnético', 'industrial'],
    variantLabel: 'Amperaje',
    variants: [
      { value: '20A' },
      { value: '30A' },
      { value: '40A' },
      { value: '50A' },
      { value: '60A' },
      { value: '70A' },
      { value: '100A' },
    ],
  },
  {
    id: 'breaker-thql-empotrable-1-polo',
    slug: 'breaker-thql-empotrable-1-polo',
    name: 'Breaker THQL Empotrable 1 Polo',
    shortDescription: 'Interruptor termomagnético tipo THQL empotrable (enchufable / plug-in) monofásico de 1 polo.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Exceline',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 8,
    tags: ['breaker', 'THQL', 'empotrable', 'enchufable', '1 polo', 'plug-in', 'termomagnético', 'electricidad'],
    variantLabel: 'Amperaje',
    variants: [
      { value: '15A' },
      { value: '20A' },
      { value: '30A' },
      { value: '40A' },
      { value: '50A' },
      { value: '60A' },
    ],
  },
  {
    id: 'breaker-thql-empotrable-2-polos',
    slug: 'breaker-thql-empotrable-2-polos',
    name: 'Breaker THQL Empotrable 2 Polos',
    shortDescription: 'Interruptor termomagnético tipo THQL empotrable (enchufable / plug-in) bifásico de 2 polos para 240V.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Exceline',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 9,
    tags: ['breaker', 'THQL', 'empotrable', 'enchufable', '2 polos', 'bifásico', 'plug-in', 'termomagnético'],
    variantLabel: 'Amperaje',
    variants: [
      { value: '20A' },
      { value: '30A' },
      { value: '40A' },
      { value: '50A' },
      { value: '60A' },
      { value: '70A' },
      { value: '100A' },
    ],
  },
  {
    id: 'breaker-thql-empotrable-3-polos',
    slug: 'breaker-thql-empotrable-3-polos',
    name: 'Breaker THQL Empotrable 3 Polos',
    shortDescription: 'Interruptor termomagnético tipo THQL empotrable (enchufable / plug-in) trifásico de 3 polos.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Exceline',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 10,
    tags: ['breaker', 'THQL', 'empotrable', 'enchufable', '3 polos', 'trifásico', 'plug-in', 'termomagnético'],
    variantLabel: 'Amperaje',
    variants: [
      { value: '20A' },
      { value: '30A' },
      { value: '40A' },
      { value: '50A' },
      { value: '60A' },
      { value: '70A' },
      { value: '100A' },
    ],
  },
  {
    id: 'breaker-termomagnetico-din-1-polo',
    slug: 'breaker-termomagnetico-din-1-polo',
    name: 'Breaker Termomagnético Riel DIN 1 Polo',
    shortDescription: 'Interruptor termomagnético modular para montaje en riel DIN monofásico de 1 polo para tableros de protección.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'Steck',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 11,
    tags: ['breaker', 'termomagnético', 'riel DIN', '1 polo', 'monofásico', 'Steck', 'CHINT', 'disyuntor'],
    variantLabel: 'Amperaje',
    variants: [
      { value: '10A' },
      { value: '16A' },
      { value: '20A' },
      { value: '25A' },
      { value: '32A' },
      { value: '40A' },
      { value: '50A' },
      { value: '63A' },
    ],
  },
  {
    id: 'breaker-termomagnetico-din-2-polos',
    slug: 'breaker-termomagnetico-din-2-polos',
    name: 'Breaker Termomagnético Riel DIN 2 Polos',
    shortDescription: 'Interruptor termomagnético modular para montaje en riel DIN bifásico de 2 polos para protección de 240V.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'CHINT',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 12,
    tags: ['breaker', 'termomagnético', 'riel DIN', '2 polos', 'bifásico', 'CHINT', 'Steck', 'disyuntor'],
    variantLabel: 'Amperaje',
    variants: [
      { value: '16A' },
      { value: '20A' },
      { value: '25A' },
      { value: '32A' },
      { value: '40A' },
      { value: '50A' },
      { value: '63A' },
    ],
  },
  {
    id: 'breaker-termomagnetico-din-3-polos',
    slug: 'breaker-termomagnetico-din-3-polos',
    name: 'Breaker Termomagnético Riel DIN 3 Polos',
    shortDescription: 'Interruptor termomagnético modular para montaje en riel DIN trifásico de 3 polos para tableros trifásicos y motores.',
    category: 'electricidad',
    categoryLabel: 'Electricidad',
    subcategory: 'tableros',
    subcategoryLabel: 'Tableros y Breakers',
    subitem: 'tableros',
    subitemLabel: 'Tableros y Breakers',
    brand: 'CHINT',
    unit: 'und',
    image: '/categoria-electricidad.webp',
    status: 'available',
    priority: 13,
    tags: ['breaker', 'termomagnético', 'riel DIN', '3 polos', 'trifásico', 'CHINT', 'Steck', 'disyuntor'],
    variantLabel: 'Amperaje',
    variants: [
      { value: '20A' },
      { value: '25A' },
      { value: '32A' },
      { value: '40A' },
      { value: '50A' },
      { value: '63A' },
    ],
  },
]
